# Generated by Django 2.1.4 on 2019-01-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('spectator', models.IntegerField()),
                ('series_type', models.IntegerField()),
                ('r_wins', models.IntegerField()),
                ('d_wins', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('roshan_respawn_timer', models.IntegerField()),
                ('r_score', models.IntegerField()),
                ('d_score', models.IntegerField()),
                ('r_tower_state', models.IntegerField()),
                ('d_tower_state', models.IntegerField()),
                ('r_barracks_state', models.IntegerField()),
                ('d_barracks_state', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
