# Generated by Django 2.1.4 on 2019-01-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_bet_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='d_team',
            field=models.ForeignKey(default=0, on_delete=None, related_name='d_team', to='matches.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='r_team',
            field=models.ForeignKey(default=0, on_delete=None, related_name='r_team', to='matches.Team'),
            preserve_default=False,
        ),
    ]
