# Generated by Django 2.1.4 on 2019-01-07 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20190107_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('hero_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hero_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.IntegerField()),
                ('hero', models.ForeignKey(on_delete=None, to='matches.Hero')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=None, to='matches.Team')),
            ],
        ),
        migrations.AddField(
            model_name='pick',
            name='player',
            field=models.ForeignKey(on_delete=None, to='matches.Player'),
        ),
        migrations.AddField(
            model_name='ban',
            name='hero',
            field=models.ForeignKey(on_delete=None, to='matches.Hero'),
        ),
        migrations.AddField(
            model_name='ban',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Match'),
        ),
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together={('match', 'hero')},
        ),
        migrations.AlterUniqueTogether(
            name='ban',
            unique_together={('match', 'hero')},
        ),
    ]
