# Generated by Django 2.1.4 on 2019-01-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20190107_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=None, to='matches.Item')),
                ('match', models.ForeignKey(on_delete=None, to='matches.Match')),
                ('player', models.ForeignKey(on_delete=None, to='matches.Player')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='item_inventory',
            unique_together={('match', 'player', 'item')},
        ),
    ]
