# Generated by Django 2.1.4 on 2019-01-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20190107_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField()),
                ('death', models.IntegerField()),
                ('assits', models.IntegerField()),
                ('last_hits', models.IntegerField()),
                ('denies', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('level', models.IntegerField()),
                ('gpm', models.IntegerField()),
                ('xpm', models.IntegerField()),
                ('ultimate_cooldown', models.IntegerField()),
                ('respawn_timer', models.IntegerField()),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('net_worth', models.IntegerField()),
                ('side', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=None, to='matches.Match')),
                ('player', models.ForeignKey(on_delete=None, to='matches.Player')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stats',
            unique_together={('match', 'player')},
        ),
    ]
