# Generated by Django 2.1.4 on 2019-01-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_auto_20190107_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
